backend:
 name: github
 repo: Flockrush/flockrush.github.io # Path to your Github repository
 branch: master # Branch to update
 publish_mode: editorial_workflow
 media_folder: "img" # Media files will be stored in the repo under images/uploads
